### PR TITLE
Bus stops bridges

### PR DESCRIPTION
**Pull request by bdon**
Fixes display of bridges shown in #67 

Assigns correct `pmap:kind` to bus stops in #163 

@wipfli

Screenshot 2023-11-11 at 08 36 21

Screenshot 2023-11-11 at 08 36 16

### CODE REVIEW

**Comment by wipfli** [comment]
Looks much better :)

**Comment by wipfli** [comment]
Bridge polygons don't seem to work here:

https://maps.protomaps.com/#map=18.46/47.3601392/8.5233257&theme=light&renderer=maplibregl&tiles=https://build.protomaps.com/20231112.pmtiles

**Comment by wipfli** [comment]
Or here: https://maps.protomaps.com/#map=16.59/47.377647/8.542377&theme=light&renderer=maplibregl&tiles=https://build.protomaps.com/20231112.pmtiles

**Comment by bdon** [comment]
https://www.openstreetmap.org/way/537126673
https://www.openstreetmap.org/way/300869313

**Comment by bdon** [comment]
@wipfli do you think those two above need `area=yes` tags? they are closed ways with `man_made=bridge` but that is ambiguous whether it is a circular bridge linear feature or a polygon.

**Comment by wipfli** [comment]
Is there a way to find out how OSM Carto renders bridge polygons? I think we should use the same logic since Carto has probably the largest impact on how people map...

**Comment by bdon** [comment]
@wipfli I think it's related to the osm2pgsql Lua tag transform in https://github.com/gravitystorm/openstreetmap-carto/blob/master/openstreetmap-carto.lua

**Pull request merged**
